use java21_shopping;

set foreign_key_checks = 0;
DROP TABLE IF EXISTS T11_CUSTOMER;
create table T11_CUSTOMER (
	C11_CUSTOMER_ID int primary key,
	C11_CUSTOMER_NAME VARCHAR(255) NOT NULL,
	C11_CUSTOMER_EMAIL VARCHAR(255) NOT NULL,
	C11_EMPLOYEE_ADDRESS VARCHAR(255) NOT NULL,
	C11_EMPLOYEE_PHONE CHAR(10) NOT NULL,
	C11_EMPLOYEE_USERNAME VARCHAR(255) NOT NULL,
	C11_EMPLOYEE_PASSWORD VARCHAR(255) NOT NULL,
    CONSTRAINT CHECK_CUSTOMER_NUMBER_PHONE CHECK (C11_EMPLOYEE_PHONE like '0%' and length(C11_EMPLOYEE_PHONE) = 10) 
);

DROP TABLE IF EXISTS T04_PAYMENT_METHOD;
CREATE TABLE T04_PAYMENT_METHOD (
	C04_PMETHOD_ID INT PRIMARY KEY,
	C04_PMETHOD_DESC VARCHAR(255) not null,
    CONSTRAINT UNQ_PAYMENT_METHOD_NAME UNIQUE(C04_PMETHOD_DESC)
);

DROP TABLE IF EXISTS T03_ORDER;
CREATE TABLE T03_ORDER (
	C03_ORDER_ID INT PRIMARY KEY,
	C03_PMETHOD_ID int not null,
	C03_CUSTOMER_ID int not null,
	C03_ORDER_TIME datetime not null,
	C03_DELIVERY_FEE float not null,
	C03_DELIVERY_ADDRESS varchar(255) not null,
	C03_RECEIVER_PHONE char(10) not null,
	C03_TOTAL_OF_MONEY float,
	constraint FK_ORDER_CUSTOMER foreign key (C03_CUSTOMER_ID)
								references T11_CUSTOMER(C11_CUSTOMER_ID),
	constraint FK_ORDER_PAYMENT_METHOD foreign key (C03_PMETHOD_ID)
								references T04_PAYMENT_METHOD(C04_PMETHOD_ID),
	 CONSTRAINT CHECK_ORDER_NUMBER_PHONE CHECK (C03_RECEIVER_PHONE like '0%' and length(C03_RECEIVER_PHONE) = 10) 
);

DROP TABLE IF EXISTS T05_ORDER_STATUS;
CREATE TABLE T05_ORDER_STATUS (
	C05_ORDER_STATUS_ID INT PRIMARY KEY,
	C05_ORDER_STATUS_DESC VARCHAR(255) NOT NULL,
	 CONSTRAINT UNQ_ORDER_STATUS_DESC UNIQUE(C05_ORDER_STATUS_DESC)
);

DROP TABLE IF EXISTS T14_ORDER_DETAIL;
CREATE TABLE T14_ORDER_DETAIL (
	C14_ORDER_ID INT,
	C14_ITEM_DETAIL_ID INT,
	C14_AMOUNT INT NOT NULL DEFAULT 0,
	PRIMARY KEY (C14_ORDER_ID, C14_ITEM_DETAIL_ID)
);

DROP TABLE IF EXISTS T15_ORDER_STATUS_DETAIL;
CREATE TABLE T15_ORDER_STATUS_DETAIL (
	C15_ORDER_ID INT,
	C15_ORDER_STATUS_ID INT,
	C15_EMPLOYEE_ID INT NOT NULL,
	C15_LAST_UPDATE DATETIME NOT NULL,
    PRIMARY KEY (C15_ORDER_ID, C15_ORDER_STATUS_ID)
);

set foreign_key_checks = 1;