use java21_shopping;

set foreign_key_checks = 0;
DROP TABLE IF EXISTS T08_TITLE;
CREATE TABLE T08_TITLE (
	C08_TITLE_ID INT PRIMARY KEY,
	C08_TITLE_NAME VARCHAR(255) NOT NULL,
	CONSTRAINT UNQ_TITLE_NAME UNIQUE(C08_TITLE_NAME)
);
DROP TABLE IF EXISTS T07_EMPLOYEE;
CREATE TABLE T07_EMPLOYEE (
	C07_EMPLOYEE_ID INT PRIMARY KEY,
	C07_EMPLOYEE_NAME VARCHAR(255) NOT NULL,
	C07_EMPLOYEE_ADDRESS VARCHAR(255) NOT NULL,
	C07_EMPLOYEE_PHONE CHAR(10) NOT NULL,
	C07_EMPLOYEE_EMAIL VARCHAR(255) NOT NULL,
	C07_EMPLOYEE_USERNAME VARCHAR(255) NOT NULL,
	C07_EMPLOYEE_PASSWORD VARCHAR(255) NOT NULL,
	C07_TITLE_ID INT NOT NULL,
    constraint FK_EMPLOYEE_ORDER foreign key (C07_TITLE_ID)
								references T08_TITLE(C08_TITLE_ID),
	CONSTRAINT CHECK_NUMBER_PHONE CHECK (C07_EMPLOYEE_PHONE like '0%' and length(C07_EMPLOYEE_PHONE) = 10)
);

set foreign_key_checks = 1;