USE JAVA21_SHOPPING;

set foreign_key_checks = 0;

DROP TABLE IF EXISTS T09_ITEM_STATISTIC;
CREATE TABLE T09_ITEM_STATISTIC (
	C09_ITEM_ID INT PRIMARY KEY,
	C09_DATE_FROM TIME NOT NULL DEFAULT '00:00',
	C09_DATE_UNITIL TIME NOT NULL DEFAULT '23:59',
	C09_SALES_AMOUNT INT,
	C09_STOCK_AMOUNT INT,
	C09_REVENUE INT,
    constraint FK_STATISTIC_ITEM foreign key (C09_ITEM_ID)
								references T01_ITEM(CO1_ITEM_ID)

);

DROP TABLE IF EXISTS T10_REVENUE;
CREATE TABLE T10_REVENUE (
	C10_RID INT PRIMARY KEY,
	C10_DATE_FROM TIME NOT NULL DEFAULT '00:00',
	C10_DATE_UNITIL TIME NOT NULL DEFAULT '23:59',
	C10_TOTAL_OF_MONEY INT DEFAULT 0
);






set foreign_key_checks = 1;