CREATE TABLE t16_material (
    C16_MATERIAL_ID INT PRIMARY KEY,
    C16_NAME VARCHAR(255) NOT NULL

);

CREATE TABLE t17_provider (
    C17_PROVIDER_ID INT PRIMARY KEY,
    C17_NAME VARCHAR(255) NOT NULL
);

ALTER TABLE t01_item
ADD C01_IMAGE_01 VARCHAR(255);

ALTER TABLE t01_item
ADD C01_IMAGE_02 VARCHAR(255);

ALTER TABLE t01_item
ADD C01_MATERIAL_ID INT;

ALTER TABLE t01_item
ADD C01_PROVIDER_ID INT;

INSERT INTO t16_material (C16_MATERIAL_ID, C16_NAME) VALUES
(1, 'Material A'),
(2, 'Material B'),
(3, 'Material C'),
(4, 'Material D'),
(5, 'Material E');

INSERT INTO t17_provider (C17_PROVIDER_ID, C17_NAME) VALUES
(1, 'Provider 1'),
(2, 'Provider 2'),
(3, 'Provider 3'),
(4, 'Provider 4'),
(5, 'Provider 5');


ALTER TABLE `t01_item`
ADD CONSTRAINT `FK_ITEM_MATERIAL`
FOREIGN KEY (`C01_MATERIAL_ID`) REFERENCES `t16_material` (`C16_MATERIAL_ID`);

ALTER TABLE `t01_item`
ADD CONSTRAINT `FK_ITEM_PROVIDER`
FOREIGN KEY (`C01_PROVIDER_ID`) REFERENCES `t17_provider` (`C17_PROVIDER_ID`);