-- 02.sql --> Liên quan đến ORDER
-- T03_ORDER, T04_PAYMENT_METHOD, T05_ORDER_STATUS, T11_CUSTOMER, T14_ORDER_DETAIL, T15_ORDER_STATUS_DETAIL
USE java21_shopping;
CREATE TABLE T04_PAYMENT_METHOD(
	C04_PMETHOD_ID INT PRIMARY KEY,
	C04_PMETHOD_DESC TEXT NOT NULL,
    CONSTRAINT CHECK_PMETHOD_DESC CHECK (C04_PMETHOD_DESC IN ('CASH', 'CREDIT', 'DEBITCARD', 'EWALLET'))
);

CREATE TABLE T11_CUSTOMER(
	C11_CUSTOMER_ID INT PRIMARY KEY,
	C11_CUSTOMER_NAME VARCHAR(100) NOT NULL,
	C11_CUSTOMER_EMAIL VARCHAR(100) NOT NULL,
	C11_EMPLOYEE_ADDRESS VARCHAR(100) NOT NULL,
	C11_EMPLOYEE_PHONE VARCHAR(11) NOT NULL,
	C11_EMPLOYEE_USERNAME VARCHAR(20) NOT NULL,
	C11_EMPLOYEE_PASSWORD VARCHAR(20) NOT NULL,
    CONSTRAINT UNQ_CUSTOMER_EMAIL UNIQUE (C11_CUSTOMER_EMAIL),
    CONSTRAINT UNQ_EMPLOYEE_PHONE UNIQUE (C11_EMPLOYEE_PHONE),
    CONSTRAINT UNQ_EMPLOYEE_USERNAME UNIQUE (C11_EMPLOYEE_USERNAME)
);

CREATE TABLE T03_ORDER(
	C03_ORDER_ID INT PRIMARY KEY,
	C03_ORDER_TIME DATETIME NOT NULL,
	C03_DELIVERY_FEE FLOAT NOT NULL,
	C03_DELIVERY_ADDRESS VARCHAR(100) NOT NULL,
	C03_RECEIVER_PHONE VARCHAR(11) NOT NULL,
	C03_TOTAL_OF_MONEY FLOAT NOT NULL,
	C03_PMETHOD_ID INT NOT NULL,
	C03_CUSTOMER_ID INT NOT NULL,
    CONSTRAINT FK_PMETHOD FOREIGN KEY (C03_PMETHOD_ID)
								 REFERENCES T04_PAYMENT_METHOD(C04_PMETHOD_ID),
    CONSTRAINT FK_CUSTOMER FOREIGN KEY (C03_CUSTOMER_ID)
								 REFERENCES T11_CUSTOMER(C11_CUSTOMER_ID)                             

);
-- Chờ xác nhận, đang đóng gói, đóng gói hoàn thành, chờ vận chuyển, đang vận chuyển. Giao hàng thành công, giao hàng thất bại, hủy đơn hàng
CREATE TABLE T05_ORDER_STATUS(
	C05_ORDER_STATUS_ID INT PRIMARY KEY,
	C05_ORDER_STATUS_DESC TEXT NOT NULL,
    CONSTRAINT CHECK_ORDER_STATUS_DESC CHECK 
    (T05_ORDER_STATUS IN ('WAIT FOR CONFIRMATION', 'PACKAGING IN PROGRESS', 'PACKAGING COMPLETED', 'WAITING FOR SHIPMENT', 'SHIPPING IN PROGRESS', 'DELIVERY SUCCESSFUL', 'DELIVERY FAILED', 'ORDER CANCELED'))
);

CREATE TABLE T14_ORDER_DETAIL(
	C14_ORDER_ID INT,
	C14_ITEM_DETAIL_ID INT,
    C14_AMOUNT INT NOT NULL,
    PRIMARY KEY(C14_ORDER_ID, C14_ITEM_DETAIL_ID),
    FOREIGN KEY (C14_ORDER_ID) REFERENCES T03_ORDER(C03_ORDER_ID),
    FOREIGN KEY (C14_ITEM_DETAIL_ID) REFERENCES T12_ITEM_DETAIL(C12_ITEM_DETAIL_ID)
);





