-- 03.sql --> Liên quan đến EMPLOYEE, TITLE
-- T07_EMPLOYEE, T08_TITLE

CREATE TABLE T08_TITLE(
	C08_TITLE_ID INT PRIMARY KEY,
	C08_TITLE_NAME VARCHAR(100)
);

CREATE TABLE T07_EMPLOYEE(
	C07_EMPLOYEE_ID INT PRIMARY KEY,
	C07_EMPLOYEE_NAME VARCHAR(100) NOT NULL,
	C07_EMPLOYEE_ADDRESS VARCHAR(100) NOT NULL,
	C07_EMPLOYEE_PHONE VARCHAR(11) NOT NULL,
	C07_EMPLOYEE_EMAIL VARCHAR(50) NOT NULL,
	C07_EMPLOYEE_USERNAME VARCHAR(50) NOT NULL,
	C07_EMPLOYEE_PASSWORD VARCHAR(50) NOT NULL,
	C07_TITLE_ID INT,
	CONSTRAINT UNQ_EMPLOYEE_EMAIL UNIQUE (C07_EMPLOYEE_EMAIL),
    CONSTRAINT UNQ_EMPLOYEE_PHONE UNIQUE (C07_EMPLOYEE_PHONE),
    CONSTRAINT UNQ_EMPLOYEE_USERNAME UNIQUE (C07_EMPLOYEE_USERNAME),
    CONSTRAINT FK_TITLE FOREIGN KEY (C07_TITLE_ID)
								 REFERENCES T08_TITLE(C08_TITLE_ID)
);

