-- 04.sql --> T09_ITEM_STATISTIC, T10_REVENUE


CREATE TABLE T09_ITEM_STATISTIC(
	C09_ITEM_ID INT,
	C09_DATE_FROM DATETIME NOT NULL,
	C09_DATE_UNITIL DATETIME NOT NULL,
	C09_SALES_AMOUNT INT NOT NULL,
	C09_REVENUE FLOAT NOT NULL,
    PRIMARY KEY (C09_ITEM_ID, C09_DATE_FROM, C09_DATE_UNITIL),
    CONSTRAINT FK_ITEM FOREIGN KEY (C09_ITEM_ID) REFERENCES T01_ITEM(C01_ITEM_ID)
);

CREATE TABLE T10_REVENUE(
	C10_RID INT,
	C10_DATE_FROM DATETIME,
	C10_DATE_UNITIL DATETIME,
	C10_TOTAL_OF_MONEY FLOAT NOT NULL,
	PRIMARY KEY (C10_DATE_FROM, C10_DATE_UNITIL)
);
SET FOREIGN_KEY_CHECKS = 1;