-- CREATE DATABASE java21_exam CHAR SET utf8mb4;
-- USE java21_exam;

SET FOREIGN_KEY_CHECKS = 0;

-- Table for Departments
CREATE TABLE T01_DEPARTMENT (
    C01_DEPT_ID INT PRIMARY KEY,
    C01_DEPT_NAME VARCHAR(100) UNIQUE NOT NULL,
    C01_MANAGER_ID INT NOT NULL,
    C01_MANAGER_START_DATE DATE NOT NULL
);
-- Sử dụng ALTER TABLE để thêm khóa ngoại
ALTER TABLE T01_DEPARTMENT
  ADD CONSTRAINT FK_T01_DEPARTMENT_EMPLOYEE FOREIGN KEY (C01_MANAGER_ID) REFERENCES T02_EMPLOYEE(C02_EMPLOYEE_ID);

-- Table for Employees
CREATE TABLE T02_EMPLOYEE (
    C02_EMPLOYEE_ID INT PRIMARY KEY,
    C02_EMPLOYEE_NAME VARCHAR(100) NOT NULL,
    C02_ADDRESS VARCHAR(255) NOT NULL,
    C02_SALARY DECIMAL(10, 2) NOT NULL,
    C02_GENDER CHAR(1) NOT NULL,
    C02_BIRTH_DATE DATE NOT NULL,
    C02_JOIN_DATE DATE NOT NULL,
    C02_DEPT_ID INT NOT NULL,
    C02_SUPERVISOR_ID INT NOT NULL,
    CONSTRAINT FK_DEPT_ID FOREIGN KEY(C02_DEPT_ID) REFERENCES T01_DEPARTMENT(C01_DEPT_ID),
    CONSTRAINT FK_SUPERVISOR_ID FOREIGN KEY(C02_SUPERVISOR_ID) REFERENCES T02_EMPLOYEE(C02_EMPLOYEE_ID)
);

-- Table for Projects
CREATE TABLE T03_PROJECT (
    C03_PROJECT_ID INT PRIMARY KEY,
    C03_PROJECT_NAME VARCHAR(100) UNIQUE NOT NULL,
    C03_START_DATE DATE NOT NULL,
    C03_END_DATE DATE NOT NULL,
    C03_REVENUE DECIMAL(15, 2) NOT NULL,
    C03_PROJECT_MANAGER_ID INT NOT NULL,
    CONSTRAINT FK_PROJECT_MANAGER_ID FOREIGN KEY(C03_PROJECT_MANAGER_ID) REFERENCES T02_EMPLOYEE(C02_EMPLOYEE_ID)
);

-- Table for Employees working on Projects
CREATE TABLE T04_JOIN_PROJECT (
    C04_EMPLOYEE_ID INT,
    C04_PROJECT_ID INT,
    C04_HOURS_WORKED DECIMAL(5, 2),
    PRIMARY KEY (C04_EMPLOYEE_ID, C04_PROJECT_ID),
    CONSTRAINT FK_EMPLOYEE_ID FOREIGN KEY(C04_EMPLOYEE_ID) REFERENCES T02_EMPLOYEE(C02_EMPLOYEE_ID),
    CONSTRAINT FK_PROJECT_ID  FOREIGN KEY(C04_PROJECT_ID) REFERENCES T03_PROJECT(C03_PROJECT_ID)
);

SET FOREIGN_KEY_CHECKS = 1;
