-- 02.sql --> Liên quan đến ORDER, STATUS, CUSTOMER
-- T03_ORDER, T04_PAYMENT_METHOD, T05_ORDER_STATUS, T11_CUSTOMER
-- T14_ORDER_DETAIL, T15_ORDER_STATUS_DETAIL
-- thiếu bảng BILL ?

-- USE java21_shopping;

CREATE TABLE T04_PAYMENT_METHOD(
	C04_PMETHOD_ID		INT PRIMARY KEY,
	C04_PMETHOD_DESC    TEXT NOT NULL
);

CREATE TABLE T11_CUSTOMER(
	C11_CUSTOMER_ID			INT PRIMARY KEY,
	C11_CUSTOMER_NAME		VARCHAR(200),
	C11_CUSTOMER_EMAIL		VARCHAR(100) NOT NULL,
	C11_CUSTOMER_ADDRESS    TEXT NOT NULL,
	C11_CUSTOMER_PHONE		VARCHAR(50) NOT NULL,
	C11_CUSTOMER_USERNAME	VARCHAR(100) NOT NULL,
	C11_CUSTOMER_PASSWORD   VARCHAR(255) NOT NULL,	
    CONSTRAINT CHECK_CUSTOMER_PHONE  CHECK (C11_CUSTOMER_PHONE REGEXP '^[0-9]+$'),
    CONSTRAINT CHECK_CUSTOMER_PASSWORD_LENGTH CHECK (LENGTH(C11_CUSTOMER_PASSWORD) BETWEEN 8 AND 255)
);

CREATE TABLE T03_ORDER(
	C03_ORDER_ID          INT PRIMARY KEY,
	C03_ORDER_TIME		  DATETIME NOT NULL,	
	C03_DELIVERY_FEE	  FLOAT NOT NULL,
	C03_DELIVERY_ADDRESS  TEXT NOT NULL,
	C03_RECEIVER_PHONE    VARCHAR(20) NOT NULL,
	C03_TOTAL_OF_MONEY	  FLOAT NOT NULL,
	C03_PMETHOD_ID        INT NOT NULL,
	C03_CUSTOMER_ID		  INT NOT NULL,
    CONSTRAINT CHECK_RECEIVER_PHONE CHECK (C03_RECEIVER_PHONE REGEXP '^[0-9]+$'),
    CONSTRAINT CHECK_DELIVERY_FEE CHECK (C03_DELIVERY_FEE >= 0),
	CONSTRAINT CHECK_TOTAL_OF_MONEY CHECK (C03_TOTAL_OF_MONEY > 0)
);
ALTER TABLE T03_ORDER
ADD CONSTRAINT FK_PMETHOD_ORDER  FOREIGN KEY (C03_PMETHOD_ID)  REFERENCES T04_PAYMENT_METHOD(C04_PMETHOD_ID),
ADD CONSTRAINT FK_CUSTOMER_ORDER FOREIGN KEY (C03_CUSTOMER_ID) REFERENCES T11_CUSTOMER(C11_CUSTOMER_ID);	

CREATE TABLE T05_ORDER_STATUS(
	C05_ORDER_STATUS_ID   INT PRIMARY KEY,
	C05_ORDER_STATUS_DESC TEXT NOT NULL
);

CREATE TABLE T14_ORDER_DETAIL(
	C14_ORDER_ID		INT,
	C14_ITEM_DETAIL_ID  INT,
	C14_AMOUNT			INT NOT NULL,
	PRIMARY KEY(C14_ORDER_ID, C14_ITEM_DETAIL_ID),
    CONSTRAINT CHECK_AMOUNT_ORDER_DETAIL CHECK(C14_AMOUNT >= 0 ),
    CONSTRAINT FK_ORDER_DETAIL_ORDER FOREIGN KEY (C14_ORDER_ID) REFERENCES T03_ORDER(C03_ORDER_ID),
	CONSTRAINT FK_ORDER_DETAIL_ITEM_DETAIL FOREIGN KEY (C14_ITEM_DETAIL_ID) REFERENCES T12_ITEM_DETAIL(C12_ITEM_DETAIL_ID)
);

CREATE TABLE T15_ORDER_STATUS_DETAIL(
	C15_ORDER_ID			INT,
	C15_ORDER_STATUS_ID 	INT,
	C15_EMPLOYEE_ID			INT NOT NULL,
	C15_LAST_UPDATE			VARCHAR(50) NOT NULL,
    PRIMARY KEY (C15_ORDER_ID, C15_ORDER_STATUS_ID)
);
ALTER TABLE T15_ORDER_STATUS_DETAIL
ADD CONSTRAINT FK_T15_ORDER_ID 		  FOREIGN KEY (C15_ORDER_ID) 		REFERENCES T03_ORDER(C03_ORDER_ID),
ADD CONSTRAINT FK_T15_ORDER_STATUS_ID FOREIGN KEY (C15_ORDER_STATUS_ID) REFERENCES T05_ORDER_STATUS(C05_ORDER_STATUS_ID),
ADD CONSTRAINT FK_T15_EMPLOYEE_ID 	  FOREIGN KEY (C15_EMPLOYEE_ID) 	REFERENCES T07_EMPLOYEE(C07_EMPLOYEE_ID)