-- 03.sql --> Lien quan den STATISTIC
-- T09_ITEM_STATISTIC, T10_REVENUE

USE java21_shopping;

CREATE TABLE T08_TITLE (
  C08_TITLE_ID INT PRIMARY KEY,
  C08_TITLE_NAME VARCHAR(30) NOT NULL
);

CREATE TABLE T07_EMPLOYEE (
  C07_EMPLOYEE_ID INT PRIMARY KEY,
  C07_EMPLOYEE_NAME VARCHAR(255) NOT NULL,
  C07_EMPLOYEE_ADDRESS VARCHAR(100) NOT NULL,
  C07_EMPLOYEE_PHONE VARCHAR(11) NOT NULL,
  C07_EMPLOYEE_EMAIL VARCHAR(50) NOT NULL,
  C07_EMPLOYEE_USERNAME VARCHAR(20) NOT NULL,
  C07_EMPLOYEE_PASSWORD VARCHAR(20) NOT NULL,
  C07_TITLE_ID INT,
  CONSTRAINT CHECK_EMPLOYEE_PHONE_LENGTH CHECK (LENGTH(C07_EMPLOYEE_PHONE) BETWEEN 10 AND 11 
                                                AND C07_EMPLOYEE_PHONE REGEXP '^[0-9]+&'),
  CONSTRAINT CHECK_C07_EMPLOYEE_PASSWORD CHECK (LENGTH(C07_EMPLOYEE_PASSWORD) >= 8
                                                AND C07_EMPLOYEE_PASSWORD REGEXP '[A-Z]'
                                                AND C07_EMPLOYEE_PASSWORD REGEXP '[@#$%^&*]'),
  CONSTRAINT FK_EMPLOYEE_TITLE FOREIGN KEY (C07_TITLE_ID) REFERENCES T08_TITLE(C08_TITLE_ID)										
);

ALTER TABLE T07_EMPLOYEE
MODIFY COLUMN C07_TITLE_ID INT NOT NULL;

ALTER TABLE T07_EMPLOYEE
ADD CONSTRAINT UNQ_EMPLOYEE_USERNAME UNIQUE (C07_EMPLOYEE_USERNAME);

CREATE TABLE T09_ITEM_STATISTIC (
  C09_ITEM_ID INT,
  C09_DATE_FROM_0H00 DATETIME,
  C09_DATE_UNTIL_23H59 DATETIME,
  C09_SALES_AMOUNT INTEGER,
  C09_REVENUE FLOAT,
  PRIMARY KEY (C09_ITEM_ID, C09_DATE_FROM_0H00, C09_DATE_UNTIL_23H59),
  CONSTRAINT CHECK_SALES_AMOUNT CHECK (C09_SALES_AMOUNT > 0),
  CONSTRAINT FK_ITEM_STATISTIC_ITEM_ID FOREIGN KEY (C09_ITEM_ID) REFERENCES T01_ITEM(C01_ITEM_ID)
);

CREATE TABLE T10_REVENUE (
  C10_RID INT,
  C10_DATE_FROM_0H00 DATETIME,
  C10_DATE_UNITIL_23H59 DATETIME,
  C10_TOTAL_OF_MONEY FLOAT NOT NULL,
  PRIMARY KEY (C10_RID, C10_DATE_FROM_0H00, C10_DATE_UNITIL_23H59)
);