-- 03.sql --> Liên quan đến EMPLOYEE, TITLE
-- T07_EMPLOYEE, T08_TITLE

USE java21_shopping;

DROP TABLE IF EXISTS T08_TITLE;
CREATE TABLE T08_TITLE(
	C08_TITLE_ID	INT PRIMARY KEY,
	C08_TITLE_NAME	VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS T07_EMPLOYEE;	
CREATE TABLE T07_EMPLOYEE(
	C07_EMPLOYEE_ID			INT PRIMARY KEY,
	C07_EMPLOYEE_NAME		VARCHAR(255) NOT NULL,
	C07_EMPLOYEE_ADDRESS	TEXT NOT NULL,
	C07_EMPLOYEE_PHONE		VARCHAR(50) NOT NULL,
	C07_EMPLOYEE_EMAIL		VARCHAR(255) NOT NULL,
	C07_EMPLOYEE_USERNAME	VARCHAR(50) NOT NULL UNIQUE,
	C07_EMPLOYEE_PASSWORD   TEXT NOT NULL,
	C07_TITLE_ID 			INT NOT NULL,
	CONSTRAINT FK_TITLE_ID FOREIGN KEY(C07_TITLE_ID) REFERENCES T08_TITLE(C08_TITLE_ID)
);