-- 03.sql --> Liên quan đến ORDER, STATUS, CUSTOMER
-- T03_ORDER, T04_PAYMENT_METHOD, T05_ORDER_STATUS, T11_CUSTOMER
-- T14_ORDER_DETAIL, T15_ORDER_STATUS_DETAIL, T07_EMPLOYEE
-- Thiếu bảng ??? BILL ???, chưa sử dụng đến bây giờ

-- disable foreign key check
-- SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS T04_PAYMENT_METHOD;
CREATE TABLE T04_PAYMENT_METHOD (
	C04_PMETHOD_ID INT PRIMARY KEY,
	C04_PMETHOD_DESC TEXT NOT NULL
);

DROP TABLE IF EXISTS T11_CUSTOMER;
CREATE TABLE T11_CUSTOMER (
	C11_CUSTOMER_ID INT PRIMARY KEY,
	C11_CUSTOMER_NAME VARCHAR(255) NOT NULL,
	C11_CUSTOMER_EMAIL VARCHAR(255) NOT NULL,
	C11_CUSTOMER_ADDRESS  TEXT,
	C11_CUSTOMER_PHONE    VARCHAR(20),
	C11_CUSTOMER_USERNAME VARCHAR(50) NOT NULL,
	C11_CUSTOMER_PASSWORD TEXT NOT NULL,
	CONSTRAINT UNQ_CUSTOMER_USERNAME UNIQUE(C11_CUSTOMER_USERNAME)
);

-- Thông thường(thực tế) nên dùng 1 trong 2 cách dưới để generate ID
-- INT PRIMARY KEY
-- AUTO INCREMENT --> tự động tăng 1 đơn vị
-- SEQUENCE --> trong mỗi table mình phải tạo ra SEQUENCE
--          --> đại diện cho việc tự động tăng primary key

-- Demo --> tự điền ID cho đẹp dữ liệu

DROP TABLE IF EXISTS T03_ORDER;
CREATE TABLE T03_ORDER (
    C03_ORDER_ID INT PRIMARY KEY,
	C03_ORDER_TIME DATETIME NOT NULL DEFAULT current_timestamp(),
	C03_DELIVERY_FEE FLOAT NOT NULL DEFAULT 0,
	C03_DELIVERY_ADDRESS TEXT NOT NULL,
	C03_RECEIVER_PHONE   VARCHAR(20) NOT NULL,
	C03_TOTAL_OF_MONEY   FLOAT NOT NULL DEFAULT 0,
	C03_PMETHOD_ID INT NOT NULL,
	C03_CUSTOMER_ID INT NOT NULL,
    CONSTRAINT CHECK_C03_DELIVERY_FEE_POSITIVE CHECK (C03_DELIVERY_FEE >= 0),
    CONSTRAINT CHECK_C03_TOTAL_OF_MONEY CHECK (C03_TOTAL_OF_MONEY >= 0),
    CONSTRAINT FK_T03_ORDER_T04_PAYMENT_METHOD FOREIGN KEY (C03_PMETHOD_ID) REFERENCES T04_PAYMENT_METHOD(C04_PMETHOD_ID),
    CONSTRAINT FK_T03_ORDER_T11_CUSTOMER FOREIGN KEY (C03_CUSTOMER_ID) REFERENCES T11_CUSTOMER(C11_CUSTOMER_ID)
);

DROP TABLE IF EXISTS T05_ORDER_STATUS;
CREATE TABLE T05_ORDER_STATUS (
	C05_ORDER_STATUS_ID INT PRIMARY KEY,
	C05_ORDER_STATUS_DESC TEXT NOT NULL
);

DROP TABLE IF EXISTS T14_ORDER_DETAIL;
CREATE TABLE T14_ORDER_DETAIL (
	C14_ORDER_ID INT,
	C14_ITEM_DETAIL_ID INT,
	C14_AMOUNT INT,
    PRIMARY KEY (C14_ORDER_ID, C14_ITEM_DETAIL_ID),
    CONSTRAINT FK_T14_ORDER_DETAIL_T03_ORDER FOREIGN KEY (C14_ORDER_ID) REFERENCES T03_ORDER(C03_ORDER_ID),
    CONSTRAINT FK_T14_ORDER_DETAIL_T12_ITEM_DETAIL FOREIGN KEY (C14_ITEM_DETAIL_ID) REFERENCES T12_ITEM_DETAIL(C12_ITEM_DETAIL_ID)
);

DROP TABLE IF EXISTS T15_ORDER_STATUS_DETAIL;
CREATE TABLE T15_ORDER_STATUS_DETAIL (
	C15_ORDER_ID INT,
	C15_ORDER_STATUS_ID INT,
	C15_EMPLOYEE_ID INT NOT NULL,
	C15_LAST_UPDATED DATETIME NOT NULL DEFAULT current_timestamp(),
    PRIMARY KEY (C15_ORDER_ID, C15_ORDER_STATUS_ID),
    CONSTRAINT FK_T15_ORDER_STATUS_DETAIL_T03_ORDER FOREIGN KEY (C15_ORDER_ID) REFERENCES T03_ORDER(C03_ORDER_ID),
    CONSTRAINT FK_T15_ORDER_STATUS_DETAIL_T05_ORDER_STATUS FOREIGN KEY (C15_ORDER_STATUS_ID) REFERENCES T05_ORDER_STATUS(C05_ORDER_STATUS_ID),
    CONSTRAINT FK_T15_ORDER_STATUS_DETAIL_T07_EMPLOYEE FOREIGN KEY (C15_EMPLOYEE_ID) REFERENCES T07_EMPLOYEE(C07_EMPLOYEE_ID)
);

-- enable foreign key check
-- SET FOREIGN_KEY_CHECKS = 1;





