
CREATE TABLE T09_ITEM_STATISTIC (
  C09_ITEM_ID INT,
  C09_DATE_FROM_0H00 DATETIME,
  C09_DATE_UNTIL_23H59 DATETIME,
  C09_SALES_AMOUNT INTEGER,
  C09_REVENUE FLOAT,
  PRIMARY KEY (C09_ITEM_ID, C09_DATE_FROM_0H00, C09_DATE_UNTIL_23H59),
  CONSTRAINT CHECK_SALES_AMOUNT CHECK (C09_SALES_AMOUNT > 0),
  CONSTRAINT FK_ITEM_STATISTIC_ITEM_ID FOREIGN KEY (C09_ITEM_ID) REFERENCES T01_ITEM(C01_ITEM_ID)
);

ALTER TABLE T09_ITEM_STATISTIC
CHANGE C09_DATE_FROM_0H00 C09_DATE_FROM DATE; 

ALTER TABLE T09_ITEM_STATISTIC
CHANGE C09_DATE_UNTIL_23H59 C09_DATE_UNTIL DATE;

ALTER TABLE T09_ITEM_STATISTIC
MODIFY C09_SALES_AMOUNT INT NOT NULL;

ALTER TABLE T09_ITEM_STATISTIC
MODIFY C09_REVENUE FLOAT NOT NULL;

CREATE TABLE T10_REVENUE (
  C10_RID INT,
  C10_DATE_FROM_0H00 DATETIME,
  C10_DATE_UNITIL_23H59 DATETIME,
  C10_TOTAL_OF_MONEY FLOAT NOT NULL,
  PRIMARY KEY (C10_RID, C10_DATE_FROM_0H00, C10_DATE_UNITIL_23H59)
);

ALTER TABLE T10_REVENUE
DROP PRIMARY KEY,  -- Loại bỏ khóa chính hiện tại
ADD PRIMARY KEY (C10_RID);  -- Thêm khóa chính mới cho cột C10_RID

ALTER TABLE T10_REVENUE
CHANGE C10_DATE_FROM_0H00 C10_DATE_FROM DATE; 

ALTER TABLE T10_REVENUE
CHANGE C10_DATE_UNITIL_23H59 C10_DATE_UNTIL DATE;

ALTER TABLE T10_REVENUE
ADD CONSTRAINT UNQ_FROM_UNTIL UNIQUE(C10_DATE_FROM, C10_DATE_UNTIL);

-- --------------------------------------------------------------------------------------------------
-- ALTER TABLES
SET FOREIGN_KEY_CHECKS = 0;

-- no need to drop primary key
-- C1
ALTER TABLE t12_item_detail 
CHANGE C12_ITEM_DETAIL_ID C12_ITEM_DETAIL_ID INT AUTO_INCREMENT;

-- C2
ALTER TABLE t12_item_detail 
MODIFY C12_ITEM_DETAIL_ID INT AUTO_INCREMENT;
 

SET FOREIGN_KEY_CHECKS = 1;