CREATE DATABASE KaraokeDB;
USE KaraokeDB;


-- Bảng KHACHHANG
CREATE TABLE KHACHHANG (
    MaKH VARCHAR(10) PRIMARY KEY,
    TenKH VARCHAR(100),
    DiaChi VARCHAR(100),
    SoDT VARCHAR(15),
    MaSoThue VARCHAR(20)
);

-- Bảng PHONG
CREATE TABLE PHONG (
    MaPhong VARCHAR(10) PRIMARY KEY,
    SoKhachToiDa INT,
    TrangThai VARCHAR(50),
    MoTa TEXT
);

-- Bảng MUCTIENGIO
CREATE TABLE MUCTIENGIO (
    MaTienGio VARCHAR(10) PRIMARY KEY,
    DonGia DECIMAL(10,2),
    MoTa TEXT
);

-- Bảng DICHVU
CREATE TABLE DICHVU (
    MaDV VARCHAR(10) PRIMARY KEY,
    TenDV VARCHAR(100),
    DonViTinh VARCHAR(50),
    DonGia DECIMAL(10,2)
);

-- Bảng HOADON
CREATE TABLE HOADON (
    MaHD VARCHAR(10) PRIMARY KEY,
    MaKH VARCHAR(10),
    MaPhong VARCHAR(10),
    MaTienGio VARCHAR(10),
    ThoiGianBatDauSD DATETIME,
    ThoiGianKetThucSD DATETIME,
    TrangThaiHD VARCHAR(50),
    FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    FOREIGN KEY (MaPhong) REFERENCES PHONG(MaPhong),
    FOREIGN KEY (MaTienGio) REFERENCES MUCTIENGIO(MaTienGio)
);

-- Bảng CHITIET_SUDUNGDV
CREATE TABLE CHITIET_SUDUNGDV (
    MaHD VARCHAR(10),
    MaDV VARCHAR(10),
    SoLuong INT,
    PRIMARY KEY (MaHD, MaDV),
    FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD),
    FOREIGN KEY (MaDV) REFERENCES DICHVU(MaDV)
);
