CREATE DATABASE IF NOT EXISTS KaraokeManagement;
USE KaraokeManagement;

-- Bảng khách hàng
CREATE TABLE KHACHHANG (
    MaKH VARCHAR(10) PRIMARY KEY,
    TenKH VARCHAR(50) NOT NULL,
    DiaChi VARCHAR(100),
    SoDT VARCHAR(15),
    MaSoThue VARCHAR(20)
);

-- Bảng mức tiền giờ
CREATE TABLE MUCTIENGIO (
    MaTienGio VARCHAR(10) PRIMARY KEY,
    DonGia DECIMAL(15,2) NOT NULL,
    MoTa TEXT
);

-- Bảng phòng
CREATE TABLE PHONG (
    MaPhong VARCHAR(10) PRIMARY KEY,
    SoKhachToiDa INT NOT NULL,
    TrangThai VARCHAR(20) DEFAULT 'Trong',
    MaTienGio VARCHAR(10),
    MoTa TEXT,
    FOREIGN KEY (MaTienGio) REFERENCES MUCTIENGIO(MaTienGio)
);

-- Bảng dịch vụ
CREATE TABLE DICHVU (
    MaDV VARCHAR(10) PRIMARY KEY,
    TenDV VARCHAR(50) NOT NULL,
    DonViTinh VARCHAR(20),
    DonGia DECIMAL(15,2) NOT NULL
);

-- Bảng hóa đơn
CREATE TABLE HOADON (
    MaHD VARCHAR(10) PRIMARY KEY,
    MaKH VARCHAR(10),
    MaPhong VARCHAR(10),
    MaTienGio VARCHAR(10),
    ThoiGianBatDauSD DATETIME NOT NULL,
    ThoiGianKetThucSD DATETIME,
    TrangThaiHD VARCHAR(20) DEFAULT 'Mo',
    FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    FOREIGN KEY (MaPhong) REFERENCES PHONG(MaPhong),
    FOREIGN KEY (MaTienGio) REFERENCES MUCTIENGIO(MaTienGio)
);

-- Bảng chi tiết sử dụng DV
CREATE TABLE CHITIET_SUDUNGDV (
    MaHD VARCHAR(10),
    MaDV VARCHAR(10),
    SoLuong INT NOT NULL,
    PRIMARY KEY (MaHD, MaDV),
    FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD),
    FOREIGN KEY (MaDV) REFERENCES DICHVU(MaDV)
);